blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, patterns


urlpatterns = [

]

urlpatterns += patterns('blog.views',
                        # Examples:
                        # url(r'^$', 'demofield.views.home', name='home'),
                        # url(r'^blog/', include('blog.urls')),
                        url(r'^$', 'post_all', name='post'),
                        url(r'^details/(?P<pk>[0-9]+)/$', 'post_one', name='post_one'),
                        url(r'^addlike/(?P<pk>[0-9]+)/$', 'addlike', name='addlike'),
                        url(r'^addcomments/(?P<pk>[0-9]+)/$', 'addcomment', name='addcomments'),
                        url(r'^page/(\d+)/$', 'post_all'),



                        )

loginsys/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, patterns


# urlpatterns = [
#
# ]

urlpatterns = patterns('loginsys.views',
                        # Examples:
                        # url(r'^$', 'demofield.views.home', name='home'),
                        # url(r'^blog/', include('blog.urls')),
                        url(r'^login/$', 'login', name='login'),
                        url(r'^logout/$', 'logout', name='logout'),
                        url(r'^register/$', 'register', name='register'),
                        )




# urlpatterns = patterns('',
#                        # Examples:
#                        # url(r'^$', 'firstapp.views.home', name='home'),
#                        # url(r'^blog/', include('blog.urls')),
#
#                        url(r'^login/$', 'loginsys.views.login'),
#                        url(r'^logout/$', 'loginsys.views.logout'),
#                        url(r'^register/$', 'loginsys.views.register'),
#
#                        )

mymodelsform/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('mymodelsform.views',
                       # Examples:
                       # url(r'^$', 'demofield.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^$', 'article_name', name='article_name'),
                       url(r'^redirect/$', 'article_redirect', name='article_redirect'),
                       )

practice/urls.py
# -*- coding: utf-8 -*-
"""practice URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf.urls.static import static  # относится к ckeditor
from django.conf import settings  # относится к ckeditor

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('school.urls', namespace='school')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^auth/', include('loginsys.urls', namespace='auth')),
    url(r'^homework/model/', include('mymodelsform.urls', namespace='mymodelsform')),
]


urlpatterns += patterns('',
                        url(r'^ckeditor/', include('ckeditor.urls')), # относится к ckeditor
                        ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # относится к ckeditor

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField # импорт ckeditor


class Blog(models.Model):
    class Meta():
        db_table = 'blog'
        verbose_name_plural = 'блоги'
        verbose_name = 'блог'

    blog_title = models.CharField(max_length=150, verbose_name='название')
    # blog_text = models.TextField(blank=True, null=True, verbose_name='текст')
    blog_text = RichTextField(blank=True, null=True, verbose_name='текст') # указание creditor в самой модели
    blog_date = models.DateField(default=timezone.now, verbose_name='дата',)
    blog_date2 = models.DateTimeField(default=timezone.now, verbose_name='дата',)
    blog_likes = models.IntegerField(default=0, verbose_name='понравилось')
    blog_author = models.CharField(default='Вячеслав Кардаш', max_length=50, verbose_name='автор')

    def __unicode__(self):
        return self.blog_title


class Comments(models.Model):
    class Meta():
        db_table = 'comments'
        verbose_name_plural = 'комментарии'
        verbose_name = 'комментарий'

    comments_text = models.TextField(verbose_name='Текст комментария', max_length=5000)
    comments_articles = models.ForeignKey(Blog)


# master test 1

blog/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from models import Comments


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['comments_text']

blog/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import Http404
from django.shortcuts import render_to_response, redirect
from blog.models import Blog, Comments
from forms import CommentForm
from django.core.context_processors import csrf
from django.core.paginator import Paginator
from django.contrib import auth


# def post_all(request):
#     i = Blog.objects.all()
#     return render_to_response('post_all.html', {'key_post_all': i})

'''
def articles(request, page_number=1):
    all_articles = Article.objects.all()
    current_page = Paginator(all_articles, 2)
    return render_to_response('articles.html', {'articles': current_page.page(page_number)})
'''


def post_all(request, page_number=1):
    all_articles = Blog.objects.all().reverse().order_by('blog_date2')
    current_page = Paginator(all_articles, 3)
    return render_to_response('post_all.html', {'key_post_all': current_page.page(page_number),
                                                'username': auth.get_user(request).username})


'''
def post_one(request, pk=1):
    return render_to_response('post_one.html', {'key_post_one': Blog.objects.get(pk=pk),
                                                'key_comments': Comments.objects.filter(comments_articles_id=pk)})
'''


def post_one(request, pk=1):
    comment_form = CommentForm
    args = {}
    args.update(csrf(request))
    args['key_post_one'] = Blog.objects.get(pk=pk)
    args['key_comments'] = Comments.objects.filter(comments_articles_id=pk)
    args['form'] = comment_form
    args['username'] = auth.get_user(request).username
    return render_to_response('post_one.html', args)


def addlike(request, pk):
    try:
        if pk in request.COOKIES:
            redirect('/blog/details/%s/' % pk)
        else:
            addlike = Blog.objects.get(pk=pk)
            addlike.blog_likes += 1
            addlike.save()
            response = redirect('/blog/details/%s/' % pk)
            response.set_cookie(pk, 'test')
            return response
            # return redirect('/blog/details/%s/' % pk)
    except ObjectDoesNotExist:
        raise Http404
    return redirect('/blog/details/%s/' % pk)


def addcomment(request, pk):
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comments_articles = Blog.objects.get(pk=pk)
            form.save()
    return redirect('/blog/details/%s/' % pk)

blog/templates/post_all.html
{% extends 'main.html' %}
{% load staticfiles %}

{% block post_all %}

    <div class="container">
        <div class="row">

            {# content block#}
            <div class="col-lg-8 col-md-8 col-sm-8">
                {% for i in key_post_all %}

                    {# preview posts #}

                    {# posts #}
                    <div class="row" id="posts">
                        <h1><a href="{% url 'blog:post_one' i.pk %}">{{ i.blog_title }}</a></h1>
                        <p>{{ i.blog_text|safe|truncatewords_html:40 }}</p>
                    </div>
                    {# end posts #}


                    {# icon posts #}
                    <div class="row" id="icon_post">
                        <div class="col-lg-3 col-md-4 col-sm-2">
                            <p class="fa fa-user fa-my"></p>  {{ i.blog_author }}
                        </div>

                        <div class="col-lg-3 col-md-4 col-sm-2">
                            <p class="fa fa-calendar fa-my"></p> {{ i.blog_date }}
                        </div>

                        <div class="col-lg-3 col-md-4 col-sm-2">
                            <p class="fa fa-thumbs-o-up fa-my"></p> {{ i.blog_likes }}
                        </div>

                        <div class="col-lg-3 col-md-4 col-sm-2">
                            <a class="btn btn-default" id="more" href="{% url 'blog:post_one' i.pk %}">читать далее</a>
                        </div>
                    </div>
                    {# end icon posts #}

                    <hr>

                {% endfor %}

                {# end preview posts #}



                {# pagination #}
                <div class="row" style="text-align: center">
                    <ul class="pagination pagination-block">

                        {% if key_post_all.has_previous %}
                            <li class=""><a href="/blog/page/{{ key_post_all.previous_page_number }}/">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><a href="">&laquo;</a></li>
                        {% endif %}

                        {% for page in key_post_all.paginator.page_range %}
                            {% if page == key_post_all.number %}
                                <li class="current, active"><a href="/blog/page/{{ page }}/">{{ page }}</a></li>
                            {% else %}
                                <li><a href="/blog/page/{{ page }}/">{{ page }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if key_post_all.has_next %}
                            <li class=""><a href="/blog/page/{{ key_post_all.next_page_number }}/">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><a href="">&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>
                {# end pagination #}

            </div>
            {# end content block#}

            {# sidebar block #}
            <div class="col-lg-4 col-md-4 col-sm-4">

                {# sidebar #}
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="list-group" id="sidebar">
                        <a href="/" class="list-group-item">
                            <h4 class="list-group-item-heading">На главную</h4>
{#                            <p class="list-group-item-text">текст</p>#}
                        </a>
                        <a href="{% url 'blog:post' %}" class="list-group-item">
                            <h4 class="list-group-item-heading">Блог</h4>
{#                            <p class="list-group-item-text">текст</p>#}
                        </a>
                        <a href="{% url 'mymodelsform:article_name' %}" class="list-group-item">
                            <h4 class="list-group-item-heading">Практика</h4>
{#                            <p class="list-group-item-text">текст</p>#}
                        </a>
                    </div>
                </div>
                {# end sidebar #}

            </div>
            {# sidebar block #}
        </div>
    </div>
{% endblock %}

blog/templates/post_one.html
{% extends 'main.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block post_one %}

    <div class="container">
        <div class="row">

            {# content #}
            <div class="col-lg-8 col-md-8 col-sm-8">

                <div class="row">
                    <h1>{{ key_post_one.blog_title }}</h1>
                    <p>{{ key_post_one.blog_text|safe|linebreaks }}</p>
                </div>

                <div class="row">
                    <div class="col-lg-12 col-md-12  col-sm-12">
                        <p class="fa fa-user fa-my"></p> {{ key_post_one.blog_author }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-9 col-md-9  col-sm-9">
                        <p class="fa fa-calendar fa-my"></p>{{ key_post_one.blog_date }}
                    </div>

                    <div class="col-lg-3 col-md-3  col-sm-3">
                        <p class="like">Понравилось: <a class="fa fa-thumbs-up" href="{% url 'blog:addlike' key_post_one.pk %}">
                            {{ key_post_one.blog_likes }}</a></p>
                    </div>
                </div>


                <div class="row" id="comments_form">

                    <div class="col-lg-offset-1 col-lg-10 col-md-offset-1 col-md-10 col-sm-offset-1 col-sm-10" id="comments">
                        <h4>Комментарии:</h4>
                    </div>

                    <div class="col-lg-offset-1 col-lg-9 col-md-offset-1 col-md-9 col-sm-offset-1 col-sm-9">

                    {% for comment in key_comments %}
                        <p style="font-style: italic" id="comments">{{ comment.comments_text }}</p>
                        <hr>
                    {%endfor %}
                        {% if username %}
                            {# form comment #}
                            <form action="{% url 'blog:addcomments' key_post_one.pk %}" method="post" class="form" >
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% buttons %}
                                    <button type="submit" class="btn btn-primary">
                                         Добавить комментарий
                                    </button>
                                {% endbuttons %}
                            </form>
                            {# end form comment #}
                        {% endif %}
                    </div>
                </div>
                    {% if username %}
                        {% else %}
                            <b class="message_comments"><a href="{% url 'auth:login' %}">Войдите</a> или
                                <a href="{% url 'auth:register' %}">зарегистрируйтесь</a>, чтобы оставить комментарий</b>
                    {% endif %}
            </div>
            {# end content #}


            {# sidebar block #}
            <div class="col-lg-4 col-md-4 col-sm-4">

                {# sidebar #}
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="list-group" id="sidebar">
                        <a href="/" class="list-group-item">
                            <h4 class="list-group-item-heading">На главную</h4>
{#                            <p class="list-group-item-text">текст</p>#}
                        </a>
                        <a href="{% url 'blog:post' %}" class="list-group-item">
                            <h4 class="list-group-item-heading">Блог</h4>
{#                            <p class="list-group-item-text">текст</p>#}
                        </a>
                        <a href="{% url 'mymodelsform:article_name' %}" class="list-group-item">
                            <h4 class="list-group-item-heading">Практика</h4>
{#                            <p class="list-group-item-text">текст</p>#}
                        </a>
                    </div>
                </div>
                {# end sidebar #}

            </div>
            {# sidebar block #}

        </div>
    </div>

{% endblock %}