blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, patterns


urlpatterns = [

]

urlpatterns += patterns('blog.views',
                        # Examples:
                        # url(r'^$', 'demofield.views.home', name='home'),
                        # url(r'^blog/', include('blog.urls')),
                        url(r'^$', 'post_all', name='post'),
                        url(r'^details/(?P<pk>[0-9]+)/$', 'post_one', name='post_one'),
                        url(r'^addlike/(?P<pk>[0-9]+)/$', 'addlike', name='addlike'),
                        url(r'^addcomments/(?P<pk>[0-9]+)/$', 'addcomment', name='addcomments'),
                        url(r'^page/(\d+)/$', 'post_all'),



                        )

loginsys/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, patterns


# urlpatterns = [
#
# ]

urlpatterns = patterns('loginsys.views',
                        # Examples:
                        # url(r'^$', 'demofield.views.home', name='home'),
                        # url(r'^blog/', include('blog.urls')),
                        url(r'^login/$', 'login', name='login'),
                        url(r'^logout/$', 'logout', name='logout'),
                        url(r'^register/$', 'register', name='register'),
                        )




# urlpatterns = patterns('',
#                        # Examples:
#                        # url(r'^$', 'firstapp.views.home', name='home'),
#                        # url(r'^blog/', include('blog.urls')),
#
#                        url(r'^login/$', 'loginsys.views.login'),
#                        url(r'^logout/$', 'loginsys.views.logout'),
#                        url(r'^register/$', 'loginsys.views.register'),
#
#                        )

mymodelsform/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('mymodelsform.views',
                       # Examples:
                       # url(r'^$', 'demofield.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^$', 'article_name', name='article_name'),
                       url(r'^redirect/$', 'article_redirect', name='article_redirect'),
                       )

practice/urls.py
# -*- coding: utf-8 -*-
"""practice URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf.urls.static import static  # относится к ckeditor
from django.conf import settings  # относится к ckeditor

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('school.urls', namespace='school')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^auth/', include('loginsys.urls', namespace='auth')),
    url(r'^homework/model/', include('mymodelsform.urls', namespace='mymodelsform')),
]


urlpatterns += patterns('',
                        url(r'^ckeditor/', include('ckeditor.urls')), # относится к ckeditor
                        ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # относится к ckeditor

templates/main.html
{% load staticfiles %}
{% load compress %}


<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Viacheslav Kardash">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Блог Вячеслава Кардаша Django/Python </title>

    <!-- Bootstrap -->
      {% compress css %}
      <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{%static 'css/my_style.css' %}" rel="stylesheet">
      <link href="{%static 'css/font-awesome.min.css' %}" rel="stylesheet">
      {% endcompress %}
{#      <link href= "{%static "fonts/glyphicons-halflings-regular.eot" %}" rel="stylesheet">#}
{#      <link href= "{%static "fonts/glyphicons-halflings-regular.svg" %}" rel="stylesheet">#}
{#      <link href= "{%static "fonts/glyphicons-halflings-regular.ttf" %}" rel="stylesheet">#}
{#      <link href= "{%static "fonts/glyphicons-halflings-regular.woff" %}" rel="stylesheet">#}
{#      <link href= "{%static "fonts/glyphicons-halflings-regular.woff2" %}" rel="stylesheet">#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      {% compress js %}
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      {% endcompress %}
    <![endif]-->
      <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top" id="header">
      <div class="container">

            {# меню для моб. устройств #}
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu">
                    <span class="sr-only">Открыть навигацию</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/"><img src="{% static 'logo.png' %}" alt=""></a>
          </div>
            {#  меню для моб. устройств end #}

            <div class="collapse navbar-collapse" id="responsive-menu">
                <ul class="nav navbar-nav col-lg-8 col-md-8 col-sm-8">
                        <li><a href="/blog/">Блог</a></li>
                        <li><a href="{% url 'mymodelsform:article_name' %}">Д/З</a></li>
                        <li><a href="http://spb-tut.ru/" target="_blank">Учиться Django/Python</a></li>
                </ul>

                <ul class="col-lg-3 col-md-3 col-sm-3">
                    <li class="button">
                            {% if username  %}
                                <a href="{% url 'auth:logout' %}">Выйти ({{ username }})</a>
                            {% else %}
                                <a href="{% url 'auth:login' %}">Войти</a> |
                                <a href="{% url 'auth:register' %}">Регистрация</a>
                            {% endif %}
                        </li>
                </ul>


            </div>
      </div>
    </div>

    <div class="container" id="site_name">
      <div class="row" id="h1_main" style="text-align: center">
          <h1>Практикум школы Бовсуновского (django/python для всех)</h1>
      </div>
    </div>

    {% block slider %}{% endblock %}

    {% block masonry %}{% endblock %}

    {% block post_all %}{% endblock %}

    {% block post_one %}{% endblock %}

    {% block forms %}{% endblock %}

    {% block login %}{% endblock %}

    {% block register %}{% endblock %}



    <div class="panel-footer">
        <div class="row">
                <div class="col-lg-offset-9 col-lg-2 col-md-offset-9 col-md-2 col-sm-offset-9 col-sm-2">
                    <p>Вячеслав Кардаш</p>
                </div>
                <div class="col-lg-offset-9 col-lg-2 col-md-offset-9 col-md-2 col-sm-offset-9 col-sm-2">
                    <p>2016г.</p>
                </div>
        </div>
    </div>

    {% compress js %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endcompress %}

  </body>

</html>